### PR TITLE
Update mission.sqm

### PR DESCRIPTION
**Pull request by paullee18**
* Change default revive timer from 300 to 3600. 
The short 5 minute revive timer seems to cause problems when mission makers forget to up it to something more reasonable.

* Add ACE logistics modules for vehicles
 Allows ACE interaction on vehicles for replacing wheels, repair, etc. Also includes modules to assign repair vehicles and engineers.

* Add ACE Pointing module
 Everyone has been talking about this for a while, but apparently it's already a part of ACE. Shouldn't be that much of an issue to have in the missions.

### CODE REVIEW

**Comment by captainblaffer** [comment]
Hi khaki, nice you're helping out with the framework.

Before you submit,

- I can agree with increasing the revive timer, but are you sure this is what everyone else wants too?

- Did you test the logistics module? are you sure players with the toolkit can repair vehicle engines etc? We probably want to keep it simple: toolkit is enough to repair. No engineer class or repair location needed.

- You changed the medical litter timer from 60 to 600. Please change that back before submit.

**Comment by Poulern** [comment]
Following in the same order.

1. Timer should be set to something reasonable if you want to increase it incase mission makers forget it. 10-15 minutes perhaps? My suggestion is 10, as that is when i go from switching screens to having arma 3 run in the background. 

1.1 I notice revive lives is 2, talking with blaffer it seems that is a good balance, I know in the past we had it at -1, which I think is a bit too easy, but from my experience 2 can be little if people mess up medicing, although on the other hand PA has gotten much more familiar with ace. 

1.2 ACE supposedly fixed litter bug, but i don't see a reason for having it longer than 60.

2. Bit torn on whenever you should require engineers to repair. I'd say for ops with armored assets everyone should be able to repair, while full repair requires an engineer/repair location, as people can at least move back without having a bad time and such.

**Comment by paullee18** [comment]
Is a 15 minute revive timer good? I'm just not sure if people would enjoy getting perma-dead after and having to spectate the rest of the mission, or just reslot and join their group again anyways.

I actually didn't mean to change the revive lives, not sure why it was set to 2 but for this I believe -1/ 0 is better to have by default. Same reasoning as the revive timer, people would just reslot anyways.

Didn't mean to have a 10 minute litter time there either, reverted it back.

Also what's the general consensus on logistics? The spare wheels worked really well during Forlorn Hope, but we never took enough damage to try and repair the vehicles themselves. If there's an armoured crew then I agree making all of them engineers, and having some kind of full-repair station/ vehicle.

**Comment by captainblaffer** [comment]
Khaki, from what you've said I believe these changes you want to make are based on what you 'feel' other people think? 

I believe it's okay to look into this, but I'd say lets discuss this together will all mission makers and get a consensus that way. 

We can organize a meeting similar to the modmeeting but it will be about this(and shorter). Mission makers who can't join can write up their thoughts before the meeting on reddit or PM.

For the logistics module we need to know what it's capable of exactly. What each setting does. Is this something you can investigate?

**Comment by Poulern** [comment]
In the interest of getting stuff done sooner rather than later I'll update the mission.sqm with the ACE pointing module, and up the revive timer to 600 seconds and changed it back to -1. 
For logistics I'll put it down as anyone can repair with toolkit(where you can only repair up to 60% damage, as is default and realistic), and give most of the vehicles extra wheels.

**Pull request closed without merging**
